export const translations = {
  en: {
    // Navigation
    nav_dashboard: "Dashboard",
    nav_companion: "Sahayta AI",
    nav_services: "Service Navigator",
    nav_report: "Report Grievance",
    nav_tracker: "Track Complaint",
    brand_sub: "AI Civic Companion",

    // Dashboard
    dash_welcome: "Welcome back, Citizen",
    dash_subtitle: "Your direct bridge to transparent, smart, and responsive civic governance.",
    dash_stat_active: "Active Grievances",
    dash_stat_resolved: "Resolved Tickets",
    dash_stat_time: "Avg Resolution",
    dash_recent_alerts: "Recent Civic Bulletins",
    dash_alert_1: "Municipal road repair scheduled for Sector 4, New Delhi starting Wednesday.",
    dash_alert_2: "Voter Registration drive extends till next Sunday. Register online or at local booths.",
    dash_alert_3: "Water pipeline upgrade in Southern zone may cause low pressure on July 9th.",
    dash_quick_actions: "Quick Access Shortcuts",
    dash_qa_chat: "Ask Sahayta AI about Aadhaar",
    dash_qa_pothole: "Report a local pothole",
    dash_qa_schemes: "Browse welfare schemes",
    dash_qa_track: "Check tracking status",

    // AI Companion
    chat_header: "Sahayta AI Companion",
    chat_subtitle: "Ask about government services, documentation rules, or lodge requests in any language.",
    chat_placeholder: "Type your query here (e.g., 'How do I apply for a PAN card?')...",
    chat_suggest_1: "What documents are needed for Aadhaar update?",
    chat_suggest_2: "Am I eligible for PM-Kisan Yojana?",
    chat_suggest_3: "How to get Ayushman Golden Card?",
    chat_suggest_4: "What are Tatkaal Passport fees?",
    chat_api_setting: "API Settings",
    chat_api_label: "Google Gemini API Key (Optional)",
    chat_api_desc: "Add your personal Gemini API key to query live AI instead of the local knowledge engine. Key is stored locally in your browser.",
    chat_api_save: "Save API Key",
    chat_api_clear: "Clear Key",
    chat_api_success: "API Key configured successfully!",
    chat_api_removed: "API Key removed. Switched to local knowledge engine.",
    chat_voice_start: "Speak Now",
    chat_voice_stop: "Stop Listening",
    chat_listen_toast: "Listening... speak clearly into your mic.",
    chat_tts_play: "Read response aloud",
    chat_mode_local: "Using Local Knowledge Engine (No Key)",
    chat_mode_live: "Gemini AI Engine Active",

    // Services
    serv_header: "Government Services & Schemes",
    serv_subtitle: "Find guidelines, eligibility criteria, and step-by-step documentation rules.",
    serv_search: "Search services by name, keyword, or department...",
    serv_cat_all: "All Services",
    serv_cat_id: "Identity & Documents",
    serv_cat_welfare: "Welfare & Schemes",
    serv_cat_utilities: "Utilities & Civic",
    serv_cat_education: "Education & Health",
    serv_btn_view: "View Document Checker",
    serv_drawer_poi: "Proof of Identity (Any One)",
    serv_drawer_poa: "Proof of Address (Any One)",
    serv_drawer_other: "Other Requirements",
    serv_drawer_apply: "Application Procedure",

    // Report
    rep_header: "File a Public Grievance",
    rep_subtitle: "Help your municipal authorities locate and fix issues in your neighborhood.",
    rep_lbl_category: "Select Issue Category",
    rep_cat_roads: "Roads & Potholes",
    rep_cat_lights: "Streetlights",
    rep_cat_waste: "Garbage & Waste",
    rep_cat_water: "Sewage & Water",
    rep_lbl_title: "Brief Title of Issue",
    rep_lbl_desc: "Detailed Description",
    rep_lbl_loc: "Location/Address Details",
    rep_lbl_photo: "Upload Supporting Photo (Optional)",
    rep_upload_placeholder: "Click or drag & drop image file to upload",
    rep_btn_submit: "Submit Grievance Ticket",
    rep_success: "Grievance registered successfully!",
    rep_err_title: "Please complete all required fields.",

    // Tracker
    track_header: "Complaint Status Tracker",
    track_subtitle: "Monitor real-time progress on unresolved neighborhood issues.",
    track_placeholder: "Enter Ticket ID (e.g. SB-10294)...",
    track_btn_search: "Track Progress",
    track_info_title: "Ticket Details",
    track_info_id: "Ticket ID",
    track_info_cat: "Category",
    track_info_status: "Current Status",
    track_info_date: "Filed On",
    track_step_submitted: "Submitted",
    track_step_review: "Under Review",
    track_step_assigned: "Assigned to Dept",
    track_step_resolved: "Resolved"
  },
  hi: {
    // Navigation
    nav_dashboard: "डैशबोर्ड",
    nav_companion: "सहायता AI",
    nav_services: "सेवा नेविगेटर",
    nav_report: "शिकायत दर्ज करें",
    nav_tracker: "शिकायत ट्रैकर",
    brand_sub: "AI नागरिक साथी",

    // Dashboard
    dash_welcome: "नमस्ते, प्रिय नागरिक",
    dash_subtitle: "पारदर्शी, स्मार्ट और उत्तरदायी नागरिक शासन के लिए आपका सीधा माध्यम।",
    dash_stat_active: "सक्रिय शिकायतें",
    dash_stat_resolved: "हल किए गए टिकट",
    dash_stat_time: "औसत निवारण",
    dash_recent_alerts: "हालिया नागरिक बुलेटिन",
    dash_alert_1: "सेक्टर 4, नई दिल्ली में बुधवार से सड़क मरम्मत का काम निर्धारित है।",
    dash_alert_2: "मतदाता पंजीकरण अभियान अगले रविवार तक बढ़ा दिया गया है। ऑनलाइन या केंद्रों पर पंजीकरण करें।",
    dash_alert_3: "दक्षिणी क्षेत्र में पानी की पाइपलाइन अपग्रेड के कारण 9 जुलाई को कम दबाव हो सकता है।",
    dash_quick_actions: "त्वरित पहुँच शॉर्टकट",
    dash_qa_chat: "आधार के बारे में सहायता AI से पूछें",
    dash_qa_pothole: "स्थानीय गड्ढे की रिपोर्ट करें",
    dash_qa_schemes: "कल्याणकारी योजनाएं देखें",
    dash_qa_track: "ट्रैकिंग स्थिति की जांच करें",

    // AI Companion
    chat_header: "सहायता AI नागरिक साथी",
    chat_subtitle: "सरकारी सेवाओं, आवश्यक दस्तावेजों के बारे में किसी भी भाषा में पूछें।",
    chat_placeholder: "अपनी पूछताछ यहाँ लिखें (जैसे: 'पैन कार्ड कैसे बनवाएं?')...",
    chat_suggest_1: "आधार अपडेट के लिए कौन से दस्तावेज चाहिए?",
    chat_suggest_2: "क्या मैं पीएम-किसान योजना के लिए पात्र हूँ?",
    chat_suggest_3: "आयुष्मान गोल्डन कार्ड कैसे प्राप्त करें?",
    chat_suggest_4: "तत्काल पासपोर्ट की फीस क्या है?",
    chat_api_setting: "API सेटिंग्स",
    chat_api_label: "गूगल जेमिनी API की (वैकल्पिक)",
    chat_api_desc: "स्थानीय डेटाबेस के बजाय सीधे जेमिनी AI का उपयोग करने के लिए अपनी API की दर्ज करें। यह आपके ब्राउज़र में सुरक्षित रहेगी।",
    chat_api_save: "API की सहेजें",
    chat_api_clear: "की हटाएं",
    chat_api_success: "API की सफलतापूर्वक सेट हो गई है!",
    chat_api_removed: "API की हटा दी गई। स्थानीय डेटाबेस का उपयोग किया जा रहा है।",
    chat_voice_start: "बोलें",
    chat_voice_stop: "सुनना बंद करें",
    chat_listen_toast: "सुन रहा हूँ... कृपया माइक में साफ़ बोलें।",
    chat_tts_play: "उत्तर बोलकर सुनाएं",
    chat_mode_local: "स्थानीय ज्ञान इंजन सक्रिय (की के बिना)",
    chat_mode_live: "जेमिनी AI इंजन सक्रिय",

    // Services
    serv_header: "सरकारी सेवाएं और योजनाएं",
    serv_subtitle: "दिशानिर्देश, पात्रता मानदंड और चरण-दर-चरण दस्तावेज़ आवश्यकताओं का पता लगाएं।",
    serv_search: "नाम, कीवर्ड या विभाग द्वारा सेवाएं खोजें...",
    serv_cat_all: "सभी सेवाएं",
    serv_cat_id: "पहचान और दस्तावेज़",
    serv_cat_welfare: "कल्याणकारी योजनाएं",
    serv_cat_utilities: "उपयोगिताएँ और नागरिक",
    serv_cat_education: "शिक्षा और स्वास्थ्य",
    serv_btn_view: "दस्तावेज़ चेकर देखें",
    serv_drawer_poi: "पहचान का प्रमाण (कोई भी एक)",
    serv_drawer_poa: "पते का प्रमाण (कोई भी एक)",
    serv_drawer_other: "अन्य आवश्यकताएं",
    serv_drawer_apply: "आवेदन की प्रक्रिया",

    // Report
    rep_header: "सार्वजनिक शिकायत दर्ज करें",
    rep_subtitle: "अपने नगर निगम अधिकारियों को स्थानीय समस्याओं का पता लगाने और उन्हें हल करने में मदद करें।",
    rep_lbl_category: "समस्या की श्रेणी चुनें",
    rep_cat_roads: "सड़कें और गड्ढे",
    rep_cat_lights: "स्ट्रीटलाइट",
    rep_cat_waste: "कचरा और अपशिष्ट",
    rep_cat_water: "सीवेज और पानी",
    rep_lbl_title: "समस्या का संक्षिप्त नाम",
    rep_lbl_desc: "विस्तृत विवरण",
    rep_lbl_loc: "स्थान/पते का विवरण",
    rep_lbl_photo: "सहायक फ़ोटो अपलोड करें (वैकल्पिक)",
    rep_upload_placeholder: "अपलोड करने के लिए क्लिक करें या फ़ाइल यहाँ खींचें",
    rep_btn_submit: "शिकायत टिकट सबमिट करें",
    rep_success: "शिकायत सफलतापूर्वक पंजीकृत हो गई!",
    rep_err_title: "कृपया सभी आवश्यक फ़ील्ड भरें।",

    // Tracker
    track_header: "शिकायत स्थिति ट्रैकर",
    track_subtitle: "अपने आस-पास की अनसुलझी समस्याओं की वास्तविक समय में प्रगति देखें।",
    track_placeholder: "टिकट आईडी दर्ज करें (जैसे: SB-10294)...",
    track_btn_search: "प्रगति ट्रैक करें",
    track_info_title: "टिकट का विवरण",
    track_info_id: "टिकट आईडी",
    track_info_cat: "श्रेणी",
    track_info_status: "वर्तमान स्थिति",
    track_info_date: "पंजीकरण की तिथि",
    track_step_submitted: "दर्ज की गई",
    track_step_review: "समीक्षा के अधीन",
    track_step_assigned: "विभाग को प्रेषित",
    track_step_resolved: "निवारण संपन्न"
  },
  ta: {
    // Navigation
    nav_dashboard: "டாஷ்போர்டு",
    nav_companion: "சஹாய்தா AI",
    nav_services: "சேவை வழிகாட்டி",
    nav_report: "புகார் பதிவு",
    nav_tracker: "புகார் டிராக்கர்",
    brand_sub: "AI குடிமகன் துணை",

    // Dashboard
    dash_welcome: "வணக்கம், குடிமகனே",
    dash_subtitle: "வெளிப்படையான மற்றும் பொறுப்பான குடிமை நிர்வாகத்திற்கான உங்களின் நேரடி இணைப்பு.",
    dash_stat_active: "செயலில் உள்ள புகார்கள்",
    dash_stat_resolved: "தீர்க்கப்பட்டவை",
    dash_stat_time: "சராசரி தீர்வு நேரம்",
    dash_recent_alerts: "அண்மை குடிமை அறிவிப்புகள்",
    dash_alert_1: "செக்டர் 4, புது தில்லியில் புதன்கிழமை முதல் சாலை பழுதுபார்க்கும் பணி திட்டமிடப்பட்டுள்ளது.",
    dash_alert_2: "வாக்காளர் பதிவு முகாம் அடுத்த ஞாயிறு வரை நீட்டிக்கப்பட்டுள்ளது. ஆன்லைனில் பதிவு செய்யவும்.",
    dash_alert_3: "தெற்கு மண்டலத்தில் குழாய் மேம்படுத்தல் காரணமாக ஜூலை 9 அன்று குறைந்த அழுத்தம் இருக்கலாம்.",
    dash_quick_actions: "விரைவான குறுக்குவழிகள்",
    dash_qa_chat: "சஹாய்தா AI-யிடம் ஆதார் பற்றி கேளுங்கள்",
    dash_qa_pothole: "சாலையோர பள்ளம் பற்றி புகார் செய்",
    dash_qa_schemes: "நலத்திட்டங்களை ஆராய்க",
    dash_qa_track: "புகாரின் நிலையை சரிபார்க்க",

    // AI Companion
    chat_header: "சஹாய்தா AI குடிமகன் துணை",
    chat_subtitle: "அரசு சேவைகள், ஆவண விதிகள் பற்றி எந்த மொழியிலும் கேளுங்கள்.",
    chat_placeholder: "உங்கள் கேள்வியை இங்கே தட்டச்சு செய்யவும்...",
    chat_suggest_1: "ஆதார் புதுப்பிப்புக்கு என்னென்ன ஆவணங்கள் தேவை?",
    chat_suggest_2: "பிஎம்-கிசான் திட்டத்திற்கு நான் தகுதியானவரா?",
    chat_suggest_3: "ஆயுஷ்மான் கோல்டன் கார்டு பெறுவது எப்படி?",
    chat_suggest_4: "தட்கல் பாஸ்போர்ட் கட்டணம் என்ன?",
    chat_api_setting: "API அமைப்புகள்",
    chat_api_label: "கூகுள் ஜெமினி API கீ (விரும்பினால்)",
    chat_api_desc: "நேரடி ஜெமினி AI-யைப் பயன்படுத்த உங்கள் API கீயை உள்ளிடவும். இது உங்கள் உலாவியில் மட்டுமே சேமிக்கப்படும்.",
    chat_api_save: "கீயைச் சேமி",
    chat_api_clear: "கீயை நீக்கு",
    chat_api_success: "API கீ வெற்றிகரமாக அமைக்கப்பட்டது!",
    chat_api_removed: "API கீ நீக்கப்பட்டது. உள்ளூர் தரவுத்தளம் பயன்படுத்தப்படுகிறது.",
    chat_voice_start: "பேசுங்கள்",
    chat_voice_stop: "கேட்பதை நிறுத்து",
    chat_listen_toast: "கேட்டுக்கொண்டிருக்கிறது... மைக்கில் தெளிவாகப் பேசுங்கள்.",
    chat_tts_play: "பதிலை சத்தமாக வாசி",
    chat_mode_local: "உள்ளூர் அறிவு இயந்திரம் செயலில் (கீ இல்லை)",
    chat_mode_live: "ஜெமினி AI இயந்திரம் செயலில்",

    // Services
    serv_header: "அரசு சேவைகள் & திட்டங்கள்",
    serv_subtitle: "வழிகாட்டுதல்கள், தகுதிகள் மற்றும் ஆவணத் தேவைகளைக் கண்டறியவும்.",
    serv_search: "பெயர் அல்லது துறை மூலம் சேவைகளைத் தேடுங்கள்...",
    serv_cat_all: "அனைத்து சேவைகள்",
    serv_cat_id: "அடையாளம் & ஆவணங்கள்",
    serv_cat_welfare: "நலத்திட்டங்கள்",
    serv_cat_utilities: "பொது பயன்பாடுகள்",
    serv_cat_education: "கல்வி & சுகாதாரம்",
    serv_btn_view: "தேவைப்படும் ஆவணங்களை சரிபார்க்க",
    serv_drawer_poi: "அடையாள சான்று (ஏதேனும் ஒன்று)",
    serv_drawer_poa: "முகவரி சான்று (ஏதேனும் ஒன்று)",
    serv_drawer_other: "இதர தேவைகள்",
    serv_drawer_apply: "விண்ணப்பிக்கும் முறை",

    // Report
    rep_header: "பொது குறை தீர்க்கும் புகார்",
    rep_subtitle: "நகராட்சி அதிகாரிகள் உங்கள் பகுதியில் உள்ள சிக்கல்களைக் கண்டறிந்து சரிசெய்ய உதவவும்.",
    rep_lbl_category: "சிக்கல் வகையைத் தேர்ந்தெடுக்கவும்",
    rep_cat_roads: "சாலைகள் & பள்ளங்கள்",
    rep_cat_lights: "தெருவிளக்குகள்",
    rep_cat_waste: "குப்பை & கழிவுகள்",
    rep_cat_water: "கழிவுநீர் & குடிநீர்",
    rep_lbl_title: "புகாரின் தலைப்பு",
    rep_lbl_desc: "விரிவான விளக்கம்",
    rep_lbl_loc: "இடம்/முகவரி விவரங்கள்",
    rep_lbl_photo: "ஆதார புகைப்படம் (விருப்பம்)",
    rep_upload_placeholder: "கோப்பைப் பதிவேற்ற கிளிக் செய்யவும் அல்லது இங்கே இழுக்கவும்",
    rep_btn_submit: "புகாரைச் சமர்ப்பி",
    rep_success: "புகார் வெற்றிகரமாகப் பதிவு செய்யப்பட்டது!",
    rep_err_title: "தேவைப்படும் அனைத்து புலங்களையும் நிரப்பவும்.",

    // Tracker
    track_header: "புகார் கண்காணிப்பு டிராக்கர்",
    track_subtitle: "உங்கள் பகுதியில் தீர்க்கப்படாத பிரச்சனைகளின் நேரடி நிலையை கண்காணிக்கவும்.",
    track_placeholder: "புகார் எண் (எ.கா: SB-10294)...",
    track_btn_search: "நிலையைத் தேடு",
    track_info_title: "புகார் விவரங்கள்",
    track_info_id: "புகார் எண்",
    track_info_cat: "வகை",
    track_info_status: "தற்போதைய நிலை",
    track_info_date: "பதிவு செய்த தேதி",
    track_step_submitted: "சமர்ப்பிக்கப்பட்டது",
    track_step_review: "பரிசீலனையில்",
    track_step_assigned: "துறைக்கு அனுப்பப்பட்டது",
    track_step_resolved: "தீர்க்கப்பட்டது"
  }
};

export function getTranslation(lang, key) {
  return translations[lang]?.[key] || translations['en']?.[key] || key;
}
